name: "Voice of Consumer Open Source Home"
markdown: redcarpet
pygments: true
url: http://localhost:4000/
navigation:
- text: Home
  icon: glyphicon glyphicon-home
  title: Home Page
  url: /index.html
- text: Features
  icon: glyphicon glyphicon-tasks
  title: Features
  url: /features.html
- text: Technical
  icon: glyphicon glyphicon-cog
  title: Projects I've Worked On
  url: /technical_details.html
- text: Roadmap
  icon: glyphicon glyphicon-road
  title: History and Future of Application
  url: /road_map.html
- text: Releases
  icon: glyphicon glyphicon-list-alt
  title: Personal Blog
  url: /release_notes.html
